### PR TITLE
Wizz-Vis Docs

### PR DESCRIPTION
**Pull request by pikislabis**

### CODE REVIEW

**Review by andresgomezfrr — APPROVED** [review]

**Comment by pablocasares** [comment]
What do you think about updating this PR to new 1.0.X WDP version?

**Comment by andresgomezfrr** [comment]
@pablocasares Updated to 1.0.X WDP

**Review by clarameniz — COMMENTED** [review]
I'm not sure if it should be like that, but there's only content in the "Wizz-Vis Widgets" section. The side menu is also lost.

**Review by clarameniz — APPROVED** [review]
My fault ^_^

**Pull request merged**
